[buildPlans.IosevkaMeKot]
family = "Iosevka MeKot"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaMeKot.ligations]
inherits = "haskell"

[buildPlans.IosevkaMeKot.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaMeKot.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaMeKot.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaMeKot.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaMeKot.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
